[versions]
agp = "8.7.3"
kotlin = "1.9.24"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
#versão hilt e ksp (a versão do ksp tem que ser a mesma do kotlin )
dagger-hilt = "2.51.1"
ksp = "1.9.24-1.0.20"
#retrofit para request
retrofit = "2.11.0"
#okttp
okhttp = "4.12.0"
#gson
gson = "2.13.2"
# lifecycle
lifecycle_version = "2.10.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

#import hilt
dagger-hilt = {module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt"}
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger-hilt"}
# import retrofit
retrofit = {module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
# Converter Gson (usa a MESMA versão do retrofit)
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

# Gson puro (opcional, só se você usar Gson direto)
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
#OkHttp
okhttp = {module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp"}
#lifecile
#view model
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle_version" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle_version" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
#para configurar o hilt no seu projeto
dagger-hilt =  {id ="com.google.dagger.hilt.android", version.ref = "dagger-hilt"}
ksp=  {id ="com.google.devtools.ksp", version.ref = "ksp"}
